// Finance types - Bank account integration and transaction tracking

import { LoopId } from "./index";

// Bank connection via SimpleFIN
export interface FinanceConnection {
  id: string;
  provider: "simplefin";
  accessUrl: string; // SimpleFIN access URL (contains credentials)
  status: "active" | "needs_reauth" | "error";
  lastSyncAt: string | null;
  lastSyncError: string | null;
  createdAt: string;
  updatedAt: string;
}

// Bank account from SimpleFIN
export interface FinanceAccount {
  id: string; // SimpleFIN account ID
  connectionId: string;
  name: string; // "BMO Chequing", "Rogers Mastercard"
  institution: string; // "Bank of Montreal", "Rogers Bank"
  institutionDomain: string; // "bmo.com"
  type: "checking" | "savings" | "credit" | "investment" | "other";
  currency: "CAD" | "USD";
  balance: number; // Current balance (cents)
  availableBalance: number | null;
  balanceDate: string;
  isHidden: boolean; // User can hide accounts
  createdAt: string;
  updatedAt: string;
}

// For split transactions
export interface TransactionSplit {
  id: string;
  amount: number; // Cents
  categoryId: string | null;
  loop: LoopId | null;
  subcategory: string | null;
  notes: string | null;
}

// Individual transaction
export interface FinanceTransaction {
  id: string; // Local ID
  externalId: string; // SimpleFIN transaction ID (for dedup)
  accountId: string;
  date: string; // YYYY-MM-DD
  postedAt: string; // ISO timestamp when posted
  transactedAt: string | null; // ISO timestamp when occurred (if available)
  amount: number; // Cents (negative = expense)
  description: string; // Original bank description
  cleanDescription: string; // Cleaned/normalized description
  pending: boolean;

  // Categorization
  categoryId: string | null; // User category
  loop: LoopId | null; // Life loop
  subcategory: string | null; // Sub-category within loop

  // User annotations
  notes: string | null;
  tags: string[];
  isReviewed: boolean; // User has confirmed categorization
  isRecurring: boolean; // Detected as recurring
  recurringGroupId: string | null;

  // Split support
  splits: TransactionSplit[] | null; // If split, original amount distributed
  parentTransactionId: string | null; // If this is a split child

  // Sync tracking
  source: "simplefin" | "csv_rogers" | "csv_bmo" | "manual";
  importedAt: string;
  updatedAt: string;
}

// User-defined categories
export interface FinanceCategory {
  id: string;
  name: string;
  icon: string;
  color: string;
  loop: LoopId; // Which life loop this belongs to
  subcategory: string | null; // Optional subcategory name
  isDefault: boolean; // Seed data vs user-created
  sortOrder: number;
  createdAt: string;
}

// Auto-categorization rules
export interface CategoryRule {
  id: string;
  categoryId: string;
  pattern: string; // Match pattern
  patternType: "contains" | "starts_with" | "regex";
  priority: number; // Higher = checked first
  matchCount: number; // Times this rule matched
  isAutoGenerated: boolean; // Created from user corrections
  createdAt: string;
}

// Recurring expense/bill (shared with Budget widget)
export interface BudgetExpense {
  id: string;
  name: string;
  amount: number;
  category: string;
  loop: LoopId;
  frequency: "monthly" | "weekly" | "bi-weekly" | "yearly" | "one-time";
  dueDate?: string;
  isPaid?: boolean;
  notes?: string;
  billingCycle?: number; // Day of month (1-31)
  totalPayable?: number; // Total remaining if finite (like loans)
  paymentMethod?: string;
  autoPay?: boolean;
  startDate?: string;
  endDate?: string;
  url?: string; // Link to pay or manage
}

// Loop budget allocation
export interface LoopBudget {
  loop: LoopId;
  budgeted: number;
}

// Finance settings
export interface FinanceSettings {
  currency: "CAD" | "USD";
  defaultCategories: boolean; // Use seed categories
  autoCategorizationEnabled: boolean;
  ruleSuggestionThreshold: number; // After N similar categorizations, suggest rule
}

// Sync status tracking
export interface FinanceSyncStatus {
  lastSyncAt: string | null;
  isSyncing: boolean;
  error: string | null;
}

// Complete finance state
export interface FinanceState {
  connections: FinanceConnection[];
  accounts: FinanceAccount[];
  transactions: FinanceTransaction[];
  categories: FinanceCategory[];
  rules: CategoryRule[];
  expenses: BudgetExpense[]; // Recurring bills (shared with Budget widget)
  loopBudgets: LoopBudget[]; // Budget allocations per loop
  monthlyIncome: number; // Monthly income for budgeting
  settings: FinanceSettings;
  syncStatus: FinanceSyncStatus;
}

// Default categories (seed data)
export const DEFAULT_FINANCE_CATEGORIES: FinanceCategory[] = [
  // Income
  {
    id: "cat_income",
    name: "Income",
    icon: "💰",
    color: "#73A58C",
    loop: "Wealth",
    subcategory: null,
    isDefault: true,
    sortOrder: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "cat_transfer",
    name: "Transfer",
    icon: "🔄",
    color: "#737390",
    loop: "Wealth",
    subcategory: null,
    isDefault: true,
    sortOrder: 1,
    createdAt: new Date().toISOString(),
  },

  // Health
  {
    id: "cat_groceries",
    name: "Groceries",
    icon: "🛒",
    color: "#73A58C",
    loop: "Health",
    subcategory: "Nutrition",
    isDefault: true,
    sortOrder: 10,
    createdAt: new Date().toISOString(),
  },
  {
    id: "cat_fitness",
    name: "Fitness & Gym",
    icon: "💪",
    color: "#73A58C",
    loop: "Health",
    subcategory: "Exercise",
    isDefault: true,
    sortOrder: 11,
    createdAt: new Date().toISOString(),
  },
  {
    id: "cat_medical",
    name: "Medical & Pharmacy",
    icon: "💊",
    color: "#73A58C",
    loop: "Health",
    subcategory: "Medical",
    isDefault: true,
    sortOrder: 12,
    createdAt: new Date().toISOString(),
  },

  // Fun
  {
    id: "cat_dining",
    name: "Dining & Restaurants",
    icon: "🍽️",
    color: "#A68BD4",
    loop: "Fun",
    subcategory: "Dining",
    isDefault: true,
    sortOrder: 20,
    createdAt: new Date().toISOString(),
  },
  {
    id: "cat_coffee",
    name: "Coffee & Drinks",
    icon: "☕",
    color: "#A68BD4",
    loop: "Fun",
    subcategory: "Dining",
    isDefault: true,
    sortOrder: 21,
    createdAt: new Date().toISOString(),
  },
  {
    id: "cat_entertainment",
    name: "Entertainment",
    icon: "🎬",
    color: "#A68BD4",
    loop: "Fun",
    subcategory: null,
    isDefault: true,
    sortOrder: 22,
    createdAt: new Date().toISOString(),
  },
  {
    id: "cat_subscriptions",
    name: "Subscriptions",
    icon: "📺",
    color: "#A68BD4",
    loop: "Fun",
    subcategory: null,
    isDefault: true,
    sortOrder: 23,
    createdAt: new Date().toISOString(),
  },

  // Maintenance
  {
    id: "cat_bills",
    name: "Bills & Utilities",
    icon: "📄",
    color: "#737390",
    loop: "Maintenance",
    subcategory: null,
    isDefault: true,
    sortOrder: 30,
    createdAt: new Date().toISOString(),
  },
  {
    id: "cat_housing",
    name: "Housing",
    icon: "🏠",
    color: "#737390",
    loop: "Maintenance",
    subcategory: null,
    isDefault: true,
    sortOrder: 31,
    createdAt: new Date().toISOString(),
  },
  {
    id: "cat_transport",
    name: "Transportation",
    icon: "🚗",
    color: "#737390",
    loop: "Maintenance",
    subcategory: null,
    isDefault: true,
    sortOrder: 32,
    createdAt: new Date().toISOString(),
  },
  {
    id: "cat_gas",
    name: "Gas & Fuel",
    icon: "⛽",
    color: "#737390",
    loop: "Maintenance",
    subcategory: null,
    isDefault: true,
    sortOrder: 33,
    createdAt: new Date().toISOString(),
  },

  // Family
  {
    id: "cat_kids",
    name: "Kids & Family",
    icon: "👨‍👩‍👧",
    color: "#E8A87C",
    loop: "Family",
    subcategory: null,
    isDefault: true,
    sortOrder: 40,
    createdAt: new Date().toISOString(),
  },
  {
    id: "cat_childcare",
    name: "Childcare",
    icon: "👶",
    color: "#E8A87C",
    loop: "Family",
    subcategory: null,
    isDefault: true,
    sortOrder: 41,
    createdAt: new Date().toISOString(),
  },

  // Work
  {
    id: "cat_business",
    name: "Business Expenses",
    icon: "💼",
    color: "#6B8FB4",
    loop: "Work",
    subcategory: null,
    isDefault: true,
    sortOrder: 50,
    createdAt: new Date().toISOString(),
  },

  // Wealth
  {
    id: "cat_savings",
    name: "Savings",
    icon: "🏦",
    color: "#F4B942",
    loop: "Wealth",
    subcategory: null,
    isDefault: true,
    sortOrder: 60,
    createdAt: new Date().toISOString(),
  },
  {
    id: "cat_investments",
    name: "Investments",
    icon: "📈",
    color: "#F4B942",
    loop: "Wealth",
    subcategory: null,
    isDefault: true,
    sortOrder: 61,
    createdAt: new Date().toISOString(),
  },

  // Catch-all
  {
    id: "cat_other",
    name: "Uncategorized",
    icon: "❓",
    color: "#737390",
    loop: "Maintenance",
    subcategory: null,
    isDefault: true,
    sortOrder: 99,
    createdAt: new Date().toISOString(),
  },
];

// Default auto-categorization rules (seed data)
export const DEFAULT_CATEGORY_RULES: CategoryRule[] = [
  // Groceries
  { id: "rule_grocery1", categoryId: "cat_groceries", pattern: "WALMART", patternType: "contains", priority: 50, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_grocery2", categoryId: "cat_groceries", pattern: "COSTCO", patternType: "contains", priority: 50, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_grocery3", categoryId: "cat_groceries", pattern: "LOBLAWS", patternType: "contains", priority: 50, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_grocery4", categoryId: "cat_groceries", pattern: "NO FRILLS", patternType: "contains", priority: 50, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_grocery5", categoryId: "cat_groceries", pattern: "SUPERSTORE", patternType: "contains", priority: 50, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_grocery6", categoryId: "cat_groceries", pattern: "METRO", patternType: "contains", priority: 40, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_grocery7", categoryId: "cat_groceries", pattern: "SOBEYS", patternType: "contains", priority: 50, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_grocery8", categoryId: "cat_groceries", pattern: "FOOD BASICS", patternType: "contains", priority: 50, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_grocery9", categoryId: "cat_groceries", pattern: "FRESHCO", patternType: "contains", priority: 50, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },

  // Coffee
  { id: "rule_coffee1", categoryId: "cat_coffee", pattern: "TIM HORTON", patternType: "contains", priority: 60, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_coffee2", categoryId: "cat_coffee", pattern: "STARBUCKS", patternType: "contains", priority: 60, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_coffee3", categoryId: "cat_coffee", pattern: "SECOND CUP", patternType: "contains", priority: 60, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },

  // Dining
  { id: "rule_dining1", categoryId: "cat_dining", pattern: "RESTAURANT", patternType: "contains", priority: 40, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_dining2", categoryId: "cat_dining", pattern: "UBER EATS", patternType: "contains", priority: 60, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_dining3", categoryId: "cat_dining", pattern: "DOORDASH", patternType: "contains", priority: 60, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_dining4", categoryId: "cat_dining", pattern: "SKIP THE DISHES", patternType: "contains", priority: 60, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_dining5", categoryId: "cat_dining", pattern: "MCDONALD", patternType: "contains", priority: 50, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },

  // Gas
  { id: "rule_gas1", categoryId: "cat_gas", pattern: "PETRO-CANADA", patternType: "contains", priority: 60, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_gas2", categoryId: "cat_gas", pattern: "SHELL", patternType: "contains", priority: 50, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_gas3", categoryId: "cat_gas", pattern: "ESSO", patternType: "contains", priority: 50, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_gas4", categoryId: "cat_gas", pattern: "PIONEER", patternType: "contains", priority: 50, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_gas5", categoryId: "cat_gas", pattern: "CANADIAN TIRE GAS", patternType: "contains", priority: 60, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },

  // Subscriptions
  { id: "rule_sub1", categoryId: "cat_subscriptions", pattern: "NETFLIX", patternType: "contains", priority: 60, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_sub2", categoryId: "cat_subscriptions", pattern: "SPOTIFY", patternType: "contains", priority: 60, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_sub3", categoryId: "cat_subscriptions", pattern: "DISNEY+", patternType: "contains", priority: 60, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_sub4", categoryId: "cat_subscriptions", pattern: "APPLE.COM/BILL", patternType: "contains", priority: 60, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_sub5", categoryId: "cat_subscriptions", pattern: "AMAZON PRIME", patternType: "contains", priority: 60, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },

  // Bills
  { id: "rule_bill1", categoryId: "cat_bills", pattern: "ROGERS", patternType: "contains", priority: 40, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_bill2", categoryId: "cat_bills", pattern: "BELL", patternType: "contains", priority: 40, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_bill3", categoryId: "cat_bills", pattern: "TELUS", patternType: "contains", priority: 40, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_bill4", categoryId: "cat_bills", pattern: "HYDRO", patternType: "contains", priority: 50, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_bill5", categoryId: "cat_bills", pattern: "ENBRIDGE", patternType: "contains", priority: 50, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },

  // Transfer patterns
  { id: "rule_transfer1", categoryId: "cat_transfer", pattern: "E-TRANSFER", patternType: "contains", priority: 70, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_transfer2", categoryId: "cat_transfer", pattern: "INTERAC", patternType: "contains", priority: 60, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_transfer3", categoryId: "cat_transfer", pattern: "TRANSFER", patternType: "contains", priority: 30, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },

  // Fitness
  { id: "rule_fit1", categoryId: "cat_fitness", pattern: "GYM", patternType: "contains", priority: 50, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_fit2", categoryId: "cat_fitness", pattern: "FITNESS", patternType: "contains", priority: 50, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_fit3", categoryId: "cat_fitness", pattern: "GOODLIFE", patternType: "contains", priority: 60, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },

  // Medical
  { id: "rule_med1", categoryId: "cat_medical", pattern: "PHARMACY", patternType: "contains", priority: 50, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_med2", categoryId: "cat_medical", pattern: "SHOPPERS DRUG", patternType: "contains", priority: 60, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
  { id: "rule_med3", categoryId: "cat_medical", pattern: "REXALL", patternType: "contains", priority: 60, matchCount: 0, isAutoGenerated: false, createdAt: new Date().toISOString() },
];

// Load expenses from Budget widget localStorage
export function loadExpensesFromLocalStorage(): BudgetExpense[] {
  try {
    const stored = localStorage.getItem("looops_expenses");
    if (stored) {
      return JSON.parse(stored);
    }
  } catch {
    // Ignore parse errors
  }
  return [];
}

// Save expenses to Budget widget localStorage (for sync)
export function saveExpensesToLocalStorage(expenses: BudgetExpense[]): void {
  localStorage.setItem("looops_expenses", JSON.stringify(expenses));
}

// Load loop budgets from localStorage
export function loadLoopBudgetsFromLocalStorage(): LoopBudget[] {
  try {
    const stored = localStorage.getItem("looops_loop_budgets");
    if (stored) {
      return JSON.parse(stored);
    }
  } catch {
    // Ignore parse errors
  }
  return [];
}

// Save loop budgets to localStorage
export function saveLoopBudgetsToLocalStorage(budgets: LoopBudget[]): void {
  localStorage.setItem("looops_loop_budgets", JSON.stringify(budgets));
}

// Load monthly income from localStorage
export function loadMonthlyIncomeFromLocalStorage(): number {
  try {
    const stored = localStorage.getItem("looops_monthly_income");
    if (stored) {
      return parseFloat(stored) || 0;
    }
  } catch {
    // Ignore parse errors
  }
  return 0;
}

// Save monthly income to localStorage
export function saveMonthlyIncomeToLocalStorage(income: number): void {
  localStorage.setItem("looops_monthly_income", income.toString());
}

// Default state factory
export function getDefaultFinanceState(): FinanceState {
  return {
    connections: [],
    accounts: [],
    transactions: [],
    categories: [...DEFAULT_FINANCE_CATEGORIES],
    rules: [...DEFAULT_CATEGORY_RULES],
    expenses: [], // Will be loaded from localStorage
    loopBudgets: [], // Will be loaded from localStorage
    monthlyIncome: 0, // Will be loaded from localStorage
    settings: {
      currency: "CAD",
      defaultCategories: true,
      autoCategorizationEnabled: true,
      ruleSuggestionThreshold: 3, // Suggest rule after 3 similar categorizations
    },
    syncStatus: {
      lastSyncAt: null,
      isSyncing: false,
      error: null,
    },
  };
}

// Helper: Format cents to currency string
export function formatFinanceCurrency(cents: number, currency: "CAD" | "USD" = "CAD"): string {
  const amount = cents / 100;
  return new Intl.NumberFormat("en-CA", {
    style: "currency",
    currency,
  }).format(amount);
}

// Helper: Parse currency string to cents
export function parseCurrencyToCents(value: string): number {
  // Remove currency symbols, commas, spaces
  const cleaned = value.replace(/[$,\s]/g, "").trim();
  const amount = parseFloat(cleaned);
  if (isNaN(amount)) return 0;
  return Math.round(amount * 100);
}

// Helper: Get category by ID
export function getCategoryById(
  categories: FinanceCategory[],
  categoryId: string | null
): FinanceCategory | undefined {
  if (!categoryId) return undefined;
  return categories.find((c) => c.id === categoryId);
}

// Helper: Get transactions for a date range
export function getTransactionsInRange(
  transactions: FinanceTransaction[],
  startDate: string,
  endDate: string
): FinanceTransaction[] {
  return transactions.filter(
    (t) => t.date >= startDate && t.date <= endDate
  );
}

// Helper: Get transactions by category
export function getTransactionsByCategory(
  transactions: FinanceTransaction[],
  categoryId: string
): FinanceTransaction[] {
  return transactions.filter((t) => t.categoryId === categoryId);
}

// Helper: Get transactions by loop
export function getTransactionsByLoop(
  transactions: FinanceTransaction[],
  loop: LoopId
): FinanceTransaction[] {
  return transactions.filter((t) => t.loop === loop);
}

// Helper: Calculate total for transactions
export function calculateTransactionTotal(
  transactions: FinanceTransaction[]
): number {
  return transactions.reduce((sum, t) => sum + t.amount, 0);
}

// Helper: Get spending by category for a period
export function getSpendingByCategory(
  transactions: FinanceTransaction[],
  categories: FinanceCategory[]
): Array<{ category: FinanceCategory; total: number; count: number }> {
  const spending = new Map<string, { total: number; count: number }>();

  // Only count expenses (negative amounts)
  transactions
    .filter((t) => t.amount < 0 && t.categoryId)
    .forEach((t) => {
      const existing = spending.get(t.categoryId!) || { total: 0, count: 0 };
      spending.set(t.categoryId!, {
        total: existing.total + Math.abs(t.amount),
        count: existing.count + 1,
      });
    });

  return categories
    .filter((c) => spending.has(c.id))
    .map((category) => ({
      category,
      ...spending.get(category.id)!,
    }))
    .sort((a, b) => b.total - a.total);
}

// Helper: Get spending by loop for a period
export function getSpendingByLoop(
  transactions: FinanceTransaction[]
): Array<{ loop: LoopId; total: number; count: number }> {
  const spending = new Map<LoopId, { total: number; count: number }>();

  // Only count expenses (negative amounts)
  transactions
    .filter((t) => t.amount < 0 && t.loop)
    .forEach((t) => {
      const existing = spending.get(t.loop!) || { total: 0, count: 0 };
      spending.set(t.loop!, {
        total: existing.total + Math.abs(t.amount),
        count: existing.count + 1,
      });
    });

  return Array.from(spending.entries())
    .map(([loop, data]) => ({ loop, ...data }))
    .sort((a, b) => b.total - a.total);
}

// Helper: Calculate net worth from accounts
export function calculateNetWorth(accounts: FinanceAccount[]): {
  assets: number;
  liabilities: number;
  netWorth: number;
} {
  let assets = 0;
  let liabilities = 0;

  accounts
    .filter((a) => !a.isHidden)
    .forEach((account) => {
      if (account.type === "credit") {
        // Credit card balance is typically negative (what you owe)
        liabilities += Math.abs(account.balance);
      } else {
        assets += account.balance;
      }
    });

  return {
    assets,
    liabilities,
    netWorth: assets - liabilities,
  };
}
